# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='post_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
